import { useState } from 'react';
import '../styles/HelpButton.css';

const HelpButton = () => {
  const [showHelp, setShowHelp] = useState(false);
  
  const toggleHelp = () => {
    setShowHelp(!showHelp);
  };
  
  return (
    <>
      <button 
        className="help-button" 
        onClick={toggleHelp} 
        aria-label="Help"
      >
        ?
      </button>
      
      {showHelp && (
        <div className="help-overlay" onClick={() => setShowHelp(false)}>
          <div className="help-modal" onClick={e => e.stopPropagation()}>
            <h2>How to Play</h2>
            <ul className="help-list">
              <li><strong>Goal:</strong> Find the AI-generated images and extract their codes</li>
              <li><strong>Step 1:</strong> Use the <code>DECODE [row] [column]</code> command to check image codes</li>
              <li><strong>Step 2:</strong> Determine which images were AI-generated by analyzing them</li>
              <li><strong>Step 3:</strong> Combine the codes from the 4 AI-generated images in order</li>
              <li><strong>Step 4:</strong> Click "ENTER CODE" and input the combined code to proceed</li>
              <li><strong>Note:</strong> Each wrong code attempt adds 1 minute to your timer!</li>
            </ul>
            <button className="close-help" onClick={() => setShowHelp(false)}>Close</button>
          </div>
        </div>
      )}
    </>
  );
};

export default HelpButton;
